name: github-event-monitor

services:

  # Object Storage
  elasticsearch:
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
    image: elasticsearch:9.4.3
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:rw

  # Event Poller
  poller:
    build: ./poller
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./secrets/rabbitmq-credentials.env
      - ./secrets/rails.env
    environment:
      - GITHUB_API_DOMAIN
      - GITHUB_API_SCHEME
    healthcheck:
      test: curl --fail localhost:3000/up
    profiles:
      - ingest

  # System of record
  postgres:
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    image: postgres:18.4-alpine3.24
    restart: always
    secrets:
      - postgres-password
    volumes:
      - postgres:/var/lib/postgresql:rw

  # GitHub API Proxy
  proxy:
    environment:
      - GITHUB_API_DOMAIN
      - GITHUB_API_PORT
      - GITHUB_API_SCHEME
    image: nginx:1.31.2-alpine3.23-slim
    volumes:
      - ./proxy/templates:/etc/nginx/templates:ro

  # Message Broker
  rabbitmq:
    env_file:
      # rabbitmq image doesn't use RABBITMQ_DEFAULT_PASS_FILE since 3.9
      - ./secrets/rabbitmq-credentials.env
    healthcheck:
      test: rabbitmq-diagnostics -q ping
    image: rabbitmq:4.3.2-management-alpine
    volumes:
      - rabbitmq:/var/lib/rabbitmq:rw

secrets:
  postgres-password:
    file: ./secrets/postgres-password.txt

volumes:
  elasticsearch:
  postgres:
  rabbitmq:
